package ed.inf.adbs.blazedb.operator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map.Entry;

import ed.inf.adbs.blazedb.SumExpressionDeparser;
import ed.inf.adbs.blazedb.entity.Tuple;
import net.sf.jsqlparser.expression.Expression;
import net.sf.jsqlparser.expression.Function;
import net.sf.jsqlparser.expression.operators.relational.ExpressionList;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.statement.select.GroupByElement;

/**
 * The {@code SumOperator} is an operator that computes the sum of specified
 * columns or expressions (e.g., using SUM()) in a given set of tuples. It can
 * operate both with and without a GROUP BY clause, depending on the input
 * query. If a GROUP BY clause is present, the sum is calculated for each
 * distinct group; otherwise, the sum is calculated for all tuples as a single
 * group.
 * 
 * <p>
 * This operator supports aggregation with functions (such as SUM()) and ignores
 * non-aggregated columns, returning them as they are. It also ensures that no
 * duplicates are present in the GROUP BY clause.
 * </p>
 *
 * <p>
 * It is designed to be used before the {@link ProjectOperator} to perform the
 * necessary aggregation before selecting specific columns in the final
 * projection.
 * </p>
 */
public class SumOperator extends Operator {

	/**
	 * The child operator to be processed by this operator.
	 */
	Operator child;

	/**
	 * The expressions used for the GROUP BY clause, if any.
	 */
	ExpressionList<Expression> groupByExpressionList;

	/**
	 * The expressions to be summed, or selected, from the tuples.
	 */
	ExpressionList<Expression> selectExpressionList;

	/**
	 * A map to store groupings and their corresponding aggregated values.
	 */
	LinkedHashMap<String, HashMap<String, Integer>> groupByHashMap;

	/**
	 * Iterator for output tuples generated by the aggregation.
	 */
	Iterator<Tuple> outputTuplesIterator;

	/**
	 * List of tuples generated by the aggregation process.
	 */
	List<Tuple> outputTuples;

	/**
	 * Constructs a {@code SumOperator} with the specified GROUP BY element and
	 * select expressions.
	 *
	 * @param groupByElement       the GROUP BY clause, or {@code null} if no
	 *                             grouping is required
	 * @param selectExpressionList the list of expressions to be selected and summed
	 */
	public SumOperator(GroupByElement groupByElement, ExpressionList<Expression> selectExpressionList) {
		if (groupByElement != null) {
			this.groupByExpressionList = groupByElement.getGroupByExpressionList();
		}
		this.selectExpressionList = selectExpressionList;
	}

	/**
	 * Computes the sum of all the child tuples based on the select expressions.
	 *
	 * @return a {@link Tuple} containing the summed values of the selected
	 *         expressions
	 */
	public Tuple computeSumOfTuples() {
		Tuple tuple;
		Tuple outputTuple = new Tuple();
		boolean firstTupleIteration = false;
		while ((tuple = child.getNextTuple()) != null) {
			if (outputTuple.getColumns().isEmpty()) {
				firstTupleIteration = true;
			} else {
				firstTupleIteration = false;
			}
			for (Expression selectExpression : selectExpressionList) {
				if (selectExpression instanceof Function) {
					Function sumFunction = (Function) selectExpression;
					Expression sumInnerExpression = (Expression) sumFunction.getParameters().getFirst();

					SumExpressionDeparser sumExpressionEvaluator = new SumExpressionDeparser(tuple);
					sumInnerExpression.accept(sumExpressionEvaluator);
					Integer output = sumExpressionEvaluator.getOutput();

					if (firstTupleIteration) {
						outputTuple.getColumns().add(sumFunction.toString());
						outputTuple.getLookup().putIfAbsent(sumFunction.toString(), output);
						continue;
					}
					Integer prevOutput = outputTuple.getLookup().get(sumFunction.toString());
					outputTuple.getLookup().put(sumFunction.toString(), prevOutput + output);
				}
			}
		}
		return outputTuple;
	}

	/**
	 * Builds a map of group-by keys and their corresponding aggregated values.
	 *
	 * @return a {@link LinkedHashMap} containing the grouped values and their
	 *         associated sums
	 */
	public LinkedHashMap<String, HashMap<String, Integer>> buildGroupByHashMap() {
		Tuple tuple;
		LinkedHashMap<String, HashMap<String, Integer>> groupByLookup = new LinkedHashMap<>();
		while ((tuple = child.getNextTuple()) != null) {
			String keyString = buildKey(tuple);
			groupByLookup.putIfAbsent(keyString, new HashMap<>());
			for (Expression selectExpression : selectExpressionList) {
				if (selectExpression instanceof Column) {
					Column column = (Column) selectExpression;
					Integer value = tuple.getLookup().get(column.toString());
					groupByLookup.get(keyString).put(column.toString(), value);
				}
				if (selectExpression instanceof Function) {
					Function sumFunction = (Function) selectExpression;
					Expression sumInnerExpression = (Expression) sumFunction.getParameters().getFirst();
					SumExpressionDeparser sumExpressionEvaluator = new SumExpressionDeparser(tuple);
					sumInnerExpression.accept(sumExpressionEvaluator);
					Integer output = sumExpressionEvaluator.getOutput();
					Integer prevOutput = groupByLookup.get(keyString).get(sumFunction.toString());

					if (prevOutput == null) {
						groupByLookup.get(keyString).putIfAbsent(sumFunction.toString(), output);
						continue;
					}
					groupByLookup.get(keyString).put(sumFunction.toString(), prevOutput + output);
				}
			}
		}
		return groupByLookup;
	}

	/**
	 * Builds the list of output tuples after grouping and summing.
	 *
	 * @return a list of {@link Tuple} objects containing the final aggregated
	 *         results
	 */
	public List<Tuple> buildOutputTuples() {
		List<Tuple> tupleList = new ArrayList<>();
		for (Entry<String, HashMap<String, Integer>> entry : groupByHashMap.entrySet()) {
			List<String> columns = new ArrayList<>();
			HashMap<String, Integer> lookup = new HashMap<>();
			for (Expression selectExpression : selectExpressionList) {
				HashMap<String, Integer> value = entry.getValue();
				if (selectExpression instanceof Column) {
					Column column = (Column) selectExpression;
					columns.add(column.toString());
					Integer columnValue = value.get(column.toString());
					lookup.put(column.toString(), columnValue);
					continue;
				}

				if (selectExpression instanceof Function) {
					Function sumFunction = (Function) selectExpression;
					Integer sumValue = value.get(sumFunction.toString());
					columns.add(sumFunction.toString());
					lookup.put(sumFunction.toString(), sumValue);
				}
			}
			Tuple outputTuple = new Tuple(columns, lookup);
			tupleList.add(outputTuple);
		}
		return tupleList;
	}

	/**
	 * Initializes the operator, processing either grouped or ungrouped tuples based
	 * on the presence of a GROUP BY clause.
	 */
	public void initialize() {
		List<Tuple> tupleList = new ArrayList<>();

		if (groupByExpressionList == null) {
			tupleList.add(computeSumOfTuples());
			this.outputTuples = tupleList;
			this.outputTuplesIterator = this.outputTuples.iterator();
			return;
		}

		this.groupByHashMap = buildGroupByHashMap();
		tupleList = buildOutputTuples();
		this.outputTuples = tupleList;
		this.outputTuplesIterator = this.outputTuples.iterator();
	}

	/**
	 * Builds a key for the GROUP BY operation, which is a concatenation of values
	 * of the grouped columns.
	 *
	 * @param tuple the tuple from which the key is generated
	 * @return a string key representing the grouped columns' values
	 */
	public String buildKey(Tuple tuple) {
		StringBuilder key = new StringBuilder();
		for (int i = 0; i < groupByExpressionList.size(); i++) {
			Expression groupByExpression = groupByExpressionList.get(i);
			Column column = (Column) groupByExpression;
			Integer columnValue = tuple.getLookup().get(column.toString());
			key.append(columnValue);

			if (i != groupByExpressionList.size() - 1) {
				key.append(",");
			}
		}
		return key.toString();
	}

	/**
	 * Sets the child operator for this sum operator.
	 *
	 * @param child the child operator to be set
	 */
	public void setChild(Operator child) {
		this.child = child;
	}

	/**
	 * Retrieves the next tuple from the output of the aggregation operation.
	 *
	 * @return the next aggregated {@link Tuple} or {@code null} if all tuples have
	 *         been processed
	 */
	@Override
	public Tuple getNextTuple() {
		if (outputTuplesIterator.hasNext()) {
			return outputTuplesIterator.next();
		}
		return null;
	}

	/**
	 * Resets the operator, so it can be re-executed from the beginning.
	 */
	@Override
	public void reset() {
		this.outputTuplesIterator = outputTuples.iterator();
	}
}
