package ed.inf.adbs.blazedb;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import ed.inf.adbs.blazedb.entity.Tuple;
import ed.inf.adbs.blazedb.operator.Operator;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.Select;

/**
 * {@code BlazeDB} is a lightweight in-memory database system designed for
 * processing SQL queries. It provides a command-line interface that accepts
 * three arguments:
 * 
 * <ul>
 * <li>database_dir: the directory containing the database files</li>
 * <li>input_file: the input SQL file containing the query to be executed</li>
 * <li>output_file: the file where the query results will be written</li>
 * </ul>
 * 
 * <p>
 * The system parses the SQL query, builds an execution plan, executes the plan,
 * and outputs the result to a file. It is designed to handle queries on a
 * lightweight in-memory database.
 * </p>
 */
public class BlazeDB {

    /**
     * Logger for the BlazeDB class.
     */
    private static final Logger logger = Logger.getLogger(BlazeDB.class.getName());

    /**
     * The main entry point of the BlazeDB system. This method expects three
     * arguments in the command line: the database directory, the input SQL file,
     * and the output file. It initializes the database, parses the SQL query,
     * builds the query execution plan, and executes it.
     *
     * @param args the command-line arguments containing the database directory,
     *             input SQL file, and output file
     * @throws FileNotFoundException if the input file is not found
     */
    public static void main(String[] args) throws FileNotFoundException {

        if (args.length != 3) {
            logger.warning("Usage: BlazeDB database_dir input_file output_file");
            return;
        }

        // get inputs
        String databaseDir = args[0];
        String inputFile = args[1];
        String outputFile = args[2];

        // initialize databaseCatalog and generate statistics
        DatabaseCatalog.getInstance().initialize(databaseDir);

        // parsing -> convert SQL query to Java object
        Statement statement = parseSQLFromFilename(inputFile);

        if (statement == null) {
            logger.warning("Statement is empty!");
            return;
        }
        Select select = (Select) statement;

        // Build query execution plan and execute it
        Operator root = new QueryPlanBuilder(select).build();
        execute(root, outputFile);
    }

    /**
     * Parses the SQL statement from a file and returns a JSQLParser
     * {@link Statement} object.
     * 
     * <p>
     * This method uses the JSQLParser library to parse the contents of the provided
     * SQL file into a {@link Statement} object. The statement is later processed to
     * extract the query details.
     * </p>
     *
     * @param filename the path to the file containing the SQL query
     * @return the parsed {@link Statement} object, or {@code null} if an error
     *         occurs
     */
    public static Statement parseSQLFromFilename(String filename) {
        try {
            return CCJSqlParserUtil.parse(new FileReader(filename));
        } catch (Exception e) {
            logger.warning("Exception occurred during parsing");
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Executes the provided query plan by repeatedly calling {@code getNextTuple()}
     * on the root operator of the query plan tree. The resulting tuples are written
     * to the specified output file.
     *
     * <p>
     * This method retrieves the result tuples generated by the operator tree and
     * writes them in CSV format to the output file. It also prints the result as a
     * formatted table to the console.
     * </p>
     *
     * @param root       the root operator of the query plan (assumed to be
     *                   non-null)
     * @param outputFile the name of the file where the results will be written
     */
    public static void execute(Operator root, String outputFile) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {

            Tuple tuple = root.getNextTuple();

            List<List<String>> table = new ArrayList<>();
            if (tuple != null) {
                table.add(tuple.getColumns());
            }

            while (tuple != null) {
                List<String> row = tuple.sortRowByColumnOrderInString();
                String csv = String.join(", ", row);
                writer.write(csv);
                writer.newLine();
                table.add(row);
                tuple = root.getNextTuple();
            }

            System.out.println(formatAsTable(table));

            root.reset();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Formats a list of rows into a human-readable table format.
     *
     * <p>
     * This method takes a list of rows, where each row is a list of strings
     * representing the columns, and returns a formatted string where the rows are
     * aligned in a table-like structure, with columns aligned based on the maximum
     * width of the values in each column.
     * </p>
     *
     * @param rows the list of rows to be formatted
     * @return a formatted table as a string
     */
    public static String formatAsTable(List<List<String>> rows) {
        int[] maxLengths = new int[rows.get(0).size()];
        for (List<String> row : rows) {
            for (int i = 0; i < row.size(); i++) {
                maxLengths[i] = Math.max(maxLengths[i], row.get(i).length());
            }
        }

        StringBuilder formatBuilder = new StringBuilder();
        for (int maxLength : maxLengths) {
            formatBuilder.append("%-").append(maxLength + 2).append("s");
        }
        String format = formatBuilder.toString();

        StringBuilder result = new StringBuilder();
        for (List<String> row : rows) {
            result.append(String.format(format, row.toArray(new String[0]))).append("\n");
        }
        return result.toString();
    }
}
